### PR TITLE
Feat/url api

### PR DESCRIPTION
**Pull request by SKotekal**
r? @philloooo 

I had to spin up a VM and edit in vim (really only familiar with :w and :q) since I was getting WindowsError with unit tests. Maybe this is cause of some format issues?

### CODE REVIEW

**Comment by philloooo** [comment]
yeah windows had some nasty wierd characters... I believe you should be able to tweak something in sublime to fix such problems?

**Comment by SKotekal** [comment]
save with encoding UTF-8? with BOM? Perhaps some other encoding?

**Comment by SKotekal** [comment]
@philloooo I tried a fix with `.gitattributes` and [line endings](https://help.github.com/articles/dealing-with-line-endings/), which got the number of differences down from ~2K to 1.5K. Not sure how to proceed from here.

**Comment by philloooo** [comment]
switch to pr to master

**Pull request closed without merging**
